rule all:
    input:
        "build/index.html",
        "build/style.css",
        "build/resources/report.html",


rule build_css:
    input:
        "build/index.html",
        "build/hero.png",
        css="src/style.css",
    output:
        "build/style.css",
    conda:
        "envs/nodejs.yaml"
    shell:
        "npm install; npx tailwindcss -i {input.css} -o {output}"


rule build_html:
    input:
        config="config.yaml",
    output:
        "build/index.html",
    conda:
        "envs/ytml.yaml"
    shell:
        "ytml src build {input.config} index.ytml.yaml"


rule copy_asset:
    input:
        "src/{asset}",
    output:
        "build/{asset}",
    shell:
        "mkdir -p $(dirname {output}); "
        "cp {input} {output}"
